/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import javax.swing.JOptionPane;

/**
 *
 * @author Loïc Cimon
 */
public class choixJoueurPanel extends javax.swing.JPanel {
    
    private final int NB_MIN, NB_MAX;

    /**
     * Creates new form choixJoueurPanel
     */
    public choixJoueurPanel(int min, int max) {
        this.NB_MIN = min;
        this.NB_MAX = max;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nbJoueur = new javax.swing.JFormattedTextField();
        jouez = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 246, 199));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utilisateur\\Documents\\NetBeansProjects\\Caylus\\Images\\titre.jpg")); // NOI18N

        jLabel2.setText("Nombre de joueurs (2 à 5) :");

        nbJoueur.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        nbJoueur.setText("2");

        jouez.setText("Jouez !");
        jouez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouezActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jouez)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nbJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nbJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jouez)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jouezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouezActionPerformed
       //Vérifie le nombre de joueur
        int nb = Integer.parseInt(nbJoueur.getText());
        if (nb >= NB_MIN && nb <= NB_MAX) {
            this.getTopLevelAncestor();
        }
        else {
            JOptionPane.showMessageDialog(this.getTopLevelAncestor(), "Le nombre de joueur saisi est incorrect.\nIl doit être compris entre 2 et 5.", "Nombre de joueur incorrect", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jouezActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jouez;
    private javax.swing.JFormattedTextField nbJoueur;
    // End of variables declaration//GEN-END:variables
}
